// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1I95KKfloDM1G2BulHstckZ1nT17q040',
    appId: '1:496161030293:web:5b68a408137a8d701e1b9c',
    messagingSenderId: '496161030293',
    projectId: 'quran-book-30ddf',
    authDomain: 'quran-book-30ddf.firebaseapp.com',
    databaseURL: 'https://quran-book-30ddf-default-rtdb.firebaseio.com',
    storageBucket: 'quran-book-30ddf.firebasestorage.app',
    measurementId: 'G-XB5D3PT0SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgePfZ0Q3Uc1Q3DDz4NIgKe5hWBQvntOc',
    appId: '1:496161030293:android:ac31567f27830f9c1e1b9c',
    messagingSenderId: '496161030293',
    projectId: 'quran-book-30ddf',
    databaseURL: 'https://quran-book-30ddf-default-rtdb.firebaseio.com',
    storageBucket: 'quran-book-30ddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonauJoBzzXn8AjRP0dWqY7As5QhqzqPo',
    appId: '1:496161030293:ios:18ff6eaf2d14573a1e1b9c',
    messagingSenderId: '496161030293',
    projectId: 'quran-book-30ddf',
    databaseURL: 'https://quran-book-30ddf-default-rtdb.firebaseio.com',
    storageBucket: 'quran-book-30ddf.firebasestorage.app',
    iosClientId: '496161030293-2l8pa49cjnevkmt329q3sa9its29nj8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonauJoBzzXn8AjRP0dWqY7As5QhqzqPo',
    appId: '1:496161030293:ios:18ff6eaf2d14573a1e1b9c',
    messagingSenderId: '496161030293',
    projectId: 'quran-book-30ddf',
    databaseURL: 'https://quran-book-30ddf-default-rtdb.firebaseio.com',
    storageBucket: 'quran-book-30ddf.firebasestorage.app',
    iosClientId: '496161030293-2l8pa49cjnevkmt329q3sa9its29nj8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1I95KKfloDM1G2BulHstckZ1nT17q040',
    appId: '1:496161030293:web:70e8b5d6478054b81e1b9c',
    messagingSenderId: '496161030293',
    projectId: 'quran-book-30ddf',
    authDomain: 'quran-book-30ddf.firebaseapp.com',
    databaseURL: 'https://quran-book-30ddf-default-rtdb.firebaseio.com',
    storageBucket: 'quran-book-30ddf.firebasestorage.app',
    measurementId: 'G-QHMBVYPWBW',
  );
}
